apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-app-config
  namespace: '${ parameters.namespace }'
data:
  message: "cloudacademy devops 2020!!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-app
  namespace: '${ parameters.namespace }'
  labels:
    source: demo
    stack: frontend
    app: echo
spec:
  replicas: 3
  selector:
    matchLabels:
      source: demo
      app: echo
  template:
    metadata:
      labels:
        source: demo
        app: echo
    spec:
      containers:
      - name: primary
        image: cloudacademydevops/echoserver
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        envFrom:
        - configMapRef:
            name: echo-app-config
---
kind: Service
apiVersion: v1
metadata:
  name: echo-service
  namespace: '${ parameters.namespace }'
spec:
  selector:
    source: demo
    app: echo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: echo-ingress
  namespace: '${ parameters.namespace }'
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: echo.cloudacademy.'${ parameters.publicip }'.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: echo-service
          servicePort: 8080
